name: "eks-ci"

on:
  push:
  pull_request:

  workflow_dispatch:


permissions:
  contents: read

jobs:
  terraform:
    name: "terraform-check"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.2"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.OC_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.OC_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OC_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Terraform Init Setup
        run: terraform init

      - name: Terraform Test
        run: terraform test
